---
title: "How to use GitHub"
subtitle: "Course notes for 'Bayesian Data Analysis & Cognitive Modeling 2017"
author: "Michael Franke"
output:
  html_document:
    theme: "cosmo"
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    number_sections: true
---

# What is GitHub?

[GitHub](https://github.com) is a web-based hosting service for [version control](https://en.wikipedia.org/wiki/Repository_(version_control)), based on [Git](https://en.wikipedia.org/wiki/Git).

# What do we need it for?

The [course website](https://michael-franke.github.io/BDACM_2017/) and all course material is hosted on GitHub in a publicly accessible [repository](https://github.com/michael-franke/BDACM_2017).

# How to get the material?

There are at least three ways to access and interact with the course material.

1. access the compiled slides and notes through the browser
2. download a complete copy of all material (including code and helper files)
3. clone a complete copy of the repository and keep it updated with Git

## Online access

You can access slides and notes from the [course website](https://michael-franke.github.io/BDACM_2017/). 

## Download a zipped copy

If you want to obtain all files and code in the [repository](https://github.com/michael-franke/BDACM_2017), you can **download** a copy even without a GitHub account. In order to do so:

1. got to the [repository](https://github.com/michael-franke/BDACM_2017)
2. click on the green button with label "clone or download"
3. download the file as a zip

The downside of this approach is that you may have to download a new zipped copy of the complete material every time something is added or changed. (And: you never really know when anything has changed.) 

## Clone & update



# More about Git & GitHub

To learn more about version control and GitHub, a good place to start are these [guides](https://guides.github.com).